# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c948355222ae64a4c7231512f0e65dc80c336ff2f1f0308ba7b372883391c208ab2f77135a71c349759fa1e189ae9f659c2c81b8c6bfc69d8ca12037f54a40c0

test:
  secret_key_base: 1aa06891ff0eac35ff64fd055104199d8bf12b9b85c6a8a642177028c58e797d3f3e35fe1c6e380161e7c1346f581998be9aa89fe8c51ef394c96697631fbf00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
